services:
  - type: web
    name: ziwa-backend
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/ziwa-0.0.1-SNAPSHOT.jar
    plan: free
    region: oregon
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_VERSION
        value: 17
